added install_ember_cli function and throw_error function

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,10 +1,7 @@
 #!/usr/bin/env bash
 
-# Logging stuff.
-function e_header()   { echo -e "\n\033[1m$@\033[0m"; }
-function e_success()  { echo -e " \033[1;32m✔\033[0m  $@"; }
-function e_error()    { echo -e " \033[1;31m✖\033[0m  $@"; }
-function e_arrow()    { echo -e " \033[1;34m➜\033[0m  $@"; }
+# Exit on error
+set -e
 
 # VARS
 export ENVIRONMENT=dev
@@ -15,17 +12,24 @@ export APP_OWNER=austin-dsc
 export APP_PATH=$WORKSPACE_PATH/$APP_NAME
 export APP_REPO=https://github.com/$APP_OWNER/$APP_NAME.git
 
+# Logging stuff.
+function e_header()   { echo -e "\n\033[1m$@\033[0m"; }
+function e_success()  { echo -e " \033[1;32m✔\033[0m  $@"; }
+function e_error()    { echo -e " \033[1;31m✖\033[0m  $@"; }
+function e_arrow()    { echo -e " \033[1;34m➜\033[0m  $@"; }
+function throw_error() { e_error $@; exit 1;}
+
 # Update the app repo
 function update_app() {
   e_header "Updating $APP_NAME"
   if [ -d $APP_PATH ]; then
     e_arrow "in $APP_PATH"
     cd $APP_PATH
-    git pull -q
+    #git pull -q
     cd $SCRIPT_PATH
     e_success "done."
   else
-    e_error "$APP_PATH does not exist."
+    throw_error "$APP_PATH does not exist."
   fi
 }
 
@@ -41,14 +45,28 @@ function clone_app() {
     if [ -d $APP_PATH ]; then
       e_success "done."
     else
-      e_error "Clone failed and $APP_PATH was not created."
+      throw_error "Clone failed and $APP_PATH was not created."
     fi
+  fi
+}
+
+function install_ember_cli() {
+  if [[ ! "$(type -P ember)" ]]; then
+    e_header "Installing the ember-cli npm package."
+    npm install -g ember-cli --silent
+    e_success "done."
+  else
+    e_header "Updating the ember-cli npm package."
+    npm update ember-cli --silent
+    e_success "done."
   fi
 }
 
 function run() {
   e_header "Setup $APP_NAME - $ENVIRONMENT"
   clone_app
+  install_ember_cli
+  install_app_packages
 }
 
 run
